// Auto-generated by scripts/generate-build-info.mjs - do not edit by hand.
// Regenerated before every dev/build/start/typecheck (see apps/web and
// apps/mobile's package.json pre* hooks) - a locally modified diff here
// after running one of those is expected, not a stray edit to revert.
export const BUILD_COMMIT = "97d0a8a";
export const BUILD_VERSION = "97d0a8a";
export const BUILD_TIME = "2026-09-14T13:16:39.384Z";
